=== jesusguevara735/XMLBasic/src/Ejercicio7/facturas.dtd
<!ELEMENT facturas (factura)*>
        <!ELEMENT factura (imagen|datosempresa|datosgenerales|contenidos|mensaje|pago)*>
        <!ELEMENT imagen (#PCDATA)>
        <!ATTLIST imagen
                imagen CDATA #REQUIRED>
        <!ELEMENT datosempresa (nombrenegocio|direccion|numero|ubicacion|email|sitioweb)*>
        <!ELEMENT nombrenegocio (#PCDATA)>
        <!ELEMENT direccion (#PCDATA)>
        <!ELEMENT numero (#PCDATA)>
        <!ELEMENT ubicacion (#PCDATA)>
        <!ELEMENT email (#PCDATA)>
        <!ELEMENT sitioweb (#PCDATA)>
        <!ELEMENT datosgenerales (cobro|envio|invoice)*>
        <!ELEMENT cobro (nombrecliente|direccion|ubicacion)*>
        <!ELEMENT nombrecliente (#PCDATA)>
        <!ELEMENT envio (nombrecliente|direccion|ubicacion)*>
        <!ELEMENT invoice (numinvoice|fechainvoice|terminos|limite)*>
        <!ELEMENT numinvoice (#PCDATA)>
        <!ELEMENT fechainvoice (#PCDATA)>
        <!ELEMENT terminos (#PCDATA)>
        <!ELEMENT limite (#PCDATA)>
        <!ELEMENT contenidos (contenido)*>
        <!ELEMENT contenido (producto_servicio|descripcion|cant_horas|calificacion|cantidad)*>
        <!ELEMENT producto_servicio (#PCDATA)>
        <!ELEMENT descripcion (#PCDATA)>
        <!ELEMENT cant_horas (#PCDATA)>
        <!ELEMENT calificacion (#PCDATA)>
        <!ELEMENT cantidad (#PCDATA)>
        <!ELEMENT mensaje (#PCDATA)>
        <!ELEMENT pago (subtotal|iva|enviocosto|total)*>
        <!ELEMENT subtotal (#PCDATA)>
        <!ELEMENT iva (#PCDATA)>
        <!ELEMENT enviocosto (#PCDATA)>
        <!ELEMENT total (#PCDATA)>

=== jesusguevara735/XMLBasic/src/Ejercicio7/factura.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE facturas SYSTEM "facturas.dtd">
<facturas>
    <factura>
        <imagen imagen="logo.png"/>
        <datosempresa>
            <nombrenegocio>Invoice</nombrenegocio>
            <direccion>calle y numero</direccion>
            <numero>numero telefonico</numero>
            <ubicacion>ciudad, estado, codigo postal</ubicacion>
            <email>correo</email>
            <sitioweb>link sitio web</sitioweb>
        </datosempresa>
        <datosgenerales>
            <cobro>
                <nombrecliente>cliente</nombrecliente>
                <direccion>calle y numero</direccion>
                <ubicacion>ciudad, estado, codigo postal</ubicacion>
            </cobro>
            <envio>
                <nombrecliente>cliente</nombrecliente>
                <direccion>calle y numero</direccion>
                <ubicacion>ciudad, estado, codigo postal</ubicacion>
            </envio>
            <invoice>
                <numinvoice>numero</numinvoice>
                <fechainvoice>fecha</fechainvoice>
                <terminos>terminos de pago</terminos>
                <limite>fecha limite</limite>
            </invoice>
        </datosgenerales>
        <contenidos>
            <contenido>
                <producto_servicio>producto o servicio</producto_servicio>
                <descripcion>descripcion del servicio</descripcion>
                <cant_horas>cantidad u horas</cant_horas>
                <calificacion>clasificacion</calificacion>
                <cantidad>cantidad</cantidad>
            </contenido>
            <contenido>
                <producto_servicio>producto o servicio</producto_servicio>
                <descripcion>descripcion del servicio</descripcion>
                <cant_horas>cantidad u horas</cant_horas>
                <calificacion>clasificacion</calificacion>
                <cantidad>cantidad</cantidad>
            </contenido>
        </contenidos>
        <mensaje>
            Hello!
            Thank you for the purchase.
            Please return this invoice with payment.
            Thanks!
        </mensaje>
        <pago>
            <subtotal>subtotal</subtotal>
            <iva>iva</iva>
            <enviocosto>costos de envio</enviocosto>
            <total>total</total>
        </pago>
    </factura>
</facturas>
